language: python
python:
- '2.7'
install:
- pip install .
script:
- python setup.py test
deploy:
  - provider: releases
    skip_cleanup: true
    api-key:
        secure: G3BbgfLFsnjamc3+JDu9eULw7L+0S/XTjxNhNCUF4BvDpi7wo8o/eUCh5/ULO3dxsvhJV+u7tQJIE6i1G10qmaZa7Rsp7nJRLjxPtWr8E3qJScO4gY6vNwXNfUGoSCTlexyS8ui/Tc6lNElmDoi5nZMPWbsUcUypwMM89Bl0ghCXtsDKbWuT23lVI9Eij6IYp8BRXhDVlC/0tcpuIKzRPh0tyiMIZgh20WgBjv0Sg6i7Rwo55x8oKm+GUh5tqzEm2pqy61QTkKVPtb3OLSLmxDjs25VuZ80ZIa9y+lyYRpmS4VQjai1xv5r4nNvYNfHEEO4LfBPk0BsDWmN2TptQ5/wFWsiw5btRKZwwisCM04FIaz5JUYV3aV1EuOU8sxQ2aGCkaC/LE5+MjVOHv6Ue28E0235fFmYj4TdDM7pXvHbS2Hu0WCn7RMgmd9nFmrO6EcFxD6C5XUSZRBOBcSQg5xVz4hemPx8pF1MDPRA/tGVnYS/a8lIQJETwB0oup2APrkmQFxjLXhMTztzBBpVl68bzZDrupBjV3B11doux+0k/RgEVN3q1atLVrrhicbNwNcZqaPcBYVoLlBGiQTtwzNf2Q+8coxmhtgP5+lX2vQ5OPG6x1MY45Y6J94vZui04Af7WWff1gUoBju5ymkVhRnPfX+zhGIAo9pGqVB7PGC8=
    name: deeputil-0.1
    tag_name: 0.1
    on:
        branch: master
        repo: deep-compute/deeputil
    # test pypi
  - provider: pypi
    distributions: "sdist bdist_wheel"
    server: https://testpypi.python.org/pypi
    skip_cleanup: true
    user: "deepcompute"
    password:
      secure: "n7FJn0pqynEEqsePAyiBIWd2NIa2wHRRRmgOX6QteG3W3RA1M3X3oCaLQll/7FGjtaw78/D6K3dk/k8aQF0W8pJr7seiBPsZGtQpMXjPBKh8dk+st6vi9xoV8UrJ46oR6nK89PLG55RECaPp82KP2MKg+qqS126H8B6LCYR3G+b9Nz7b0F6E4AW+VhjMnu75hngNNQt8oP1RuVKXiOStA59GZn9L0iIonZNhezHNqvCuk151x0/dUdcD4s4J1qyoGAWQAut1hrZZJP5mNdAzP40b8IyyHCvHWlGHQZ7P+AHn0Li/00l30uEJ5Qy+CD4TcHM/YQLeSb4bhMRQNvTmI+0G69AELyouV0lOs85lkz5l1XsnqtbzA18Rd2ylGUqro/to/LUdbIyB+udWCRk7r9YA9pbr6Jw8vp9moHti+1wiuwgTnq21IUIVXyV59nb97rfb/ZgDzPU2v54AepAYMm5VlQqCFdtWcFDXeuNIAuQ7cO0w02nFppdh4UMbyw6R14v4NY/VPbJNONr7rZRAV1BRrZ4ati/oMq68g0OL3WnG3t8Nsb2H34SZdRtQjNvNGudQpoyhMFGNBAF5JvbEIUvgknFz6hiFmTiijDLlrupQiJXkRRRX+rlE8xwZos9LJqZfaOyEL2WsEI0WR68A3xM2D8lQ/+qgGe0uaP06pa4="
    on:
      branch: master
      tags: false
    # pypi
  - provider: pypi
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    user: "deepcompute"
    password:
      secure: "n7FJn0pqynEEqsePAyiBIWd2NIa2wHRRRmgOX6QteG3W3RA1M3X3oCaLQll/7FGjtaw78/D6K3dk/k8aQF0W8pJr7seiBPsZGtQpMXjPBKh8dk+st6vi9xoV8UrJ46oR6nK89PLG55RECaPp82KP2MKg+qqS126H8B6LCYR3G+b9Nz7b0F6E4AW+VhjMnu75hngNNQt8oP1RuVKXiOStA59GZn9L0iIonZNhezHNqvCuk151x0/dUdcD4s4J1qyoGAWQAut1hrZZJP5mNdAzP40b8IyyHCvHWlGHQZ7P+AHn0Li/00l30uEJ5Qy+CD4TcHM/YQLeSb4bhMRQNvTmI+0G69AELyouV0lOs85lkz5l1XsnqtbzA18Rd2ylGUqro/to/LUdbIyB+udWCRk7r9YA9pbr6Jw8vp9moHti+1wiuwgTnq21IUIVXyV59nb97rfb/ZgDzPU2v54AepAYMm5VlQqCFdtWcFDXeuNIAuQ7cO0w02nFppdh4UMbyw6R14v4NY/VPbJNONr7rZRAV1BRrZ4ati/oMq68g0OL3WnG3t8Nsb2H34SZdRtQjNvNGudQpoyhMFGNBAF5JvbEIUvgknFz6hiFmTiijDLlrupQiJXkRRRX+rlE8xwZos9LJqZfaOyEL2WsEI0WR68A3xM2D8lQ/+qgGe0uaP06pa4="
    on:
      branch: master
      # only when there is a release it will update pypi
      tags: true
